version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:postgres@35.197.155.15:5432/ledmoa
      NEXTAUTH_SECRET: vuongdeptrai
      NEXTAUTH_URL: http://localhost:3000
      SITE_URL: https://ledmoa.co.kr
      LOGO_URL: https://res.cloudinary.com/decerwuo3/image/upload/v1703406804/logo_light.jpg
