version: "3.8"

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    
    # use docker compose to watch for changes and rebuild the container
    # develop:
    #   watch:
    #     - path: ./package.json
    #       action: rebuild
    #     - path: ./next.config.mjs
    #       action: rebuild
    #     - path: ./package-lock.json
    #       action: rebuild
    #     - path: .
    #       target: /app
    #       action: sync
    
    # define the environment variables
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:postgres@35.197.155.15:5432/ledmoa
      NEXTAUTH_SECRET: vuongdeptrai
      NEXTAUTH_URL: http://localhost:3000
      SITE_URL: https://ledmoa.co.kr
      LOGO_URL: https://res.cloudinary.com/decerwuo3/image/upload/v1703406804/logo_light.jpg
